# See https://github.com/virtual-kubelet/virtual-kubelet/issues/210
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtual-kubelet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:node:virtual-kubelet
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:node:virtual-kubelet-win