apiVersion: v1
kind: LimitRange
metadata:
  name: vk-default-request
  namespace: kube-system
spec:
  limits:
  - defaultRequest:
      cpu: 1
      memory: 1G
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vk-default-request
  namespace: kube-public
spec:
  limits:
  - defaultRequest:
      cpu: 1
      memory: 1G
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: vk-default-request
  namespace: default
spec:
  limits:
  - defaultRequest:
      cpu: 1
      memory: 1G
    type: Container